#!/usr/bin/env bash
# scripts/build.sh — build the beastty-core wasm into www/pkg
#
# Invariants (per Phase 2 RESEARCH Pitfall #5):
# - `cd "$(dirname "$0")/.."` makes the script idempotent under any cwd.
# - `--out-dir ../../www/pkg` is resolved RELATIVE TO THE CRATE's Cargo.toml
#   directory (crates/beastty-core/), which places files in
#   <repo-root>/www/pkg/ regardless of where the script is invoked from.
# - `--target web` emits an ES-module-loadable pkg/ (no bundler, no Node).
# - `--release` is default; listed explicitly.
# - Add `--no-opt` if wasm-opt is not on PATH (RESEARCH Pitfall #6).
#
# Usage:
#   ./scripts/build.sh
#   bash scripts/build.sh
#
# Output files (all gitignored):
#   www/pkg/beastty_core.js          — ES-module glue
#   www/pkg/beastty_core_bg.wasm     — compiled wasm binary
#   www/pkg/beastty_core.d.ts        — TypeScript type defs
#   www/pkg/beastty_core_bg.wasm.d.ts
#   www/pkg/package.json                 — emitted but not used (no npm)

set -euo pipefail
cd "$(dirname "$0")/.."

wasm-pack build crates/beastty-core \
    --target web \
    --out-dir ../../www/pkg \
    --release

# Build stamp (Defect 00001) — emit a git SHA into www/pkg/ so every defect
# report self-identifies the EXACT running build, independent of whether we
# remembered to bump package.json. pkg/ is gitignored, so this is regenerated
# on every build and never committed. www/main.js loads it into the Debug pane
# with a graceful fallback, so a build done via raw `wasm-pack` (per
# www/README.md) that skips this script still boots — the stamp just reads
# "unknown (unbuilt)".
build_sha="unknown"
built_at="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
if git rev-parse --git-dir >/dev/null 2>&1; then
    build_sha="$(git rev-parse --short=12 HEAD 2>/dev/null || echo unknown)"
    # Mark builds made from an uncommitted working tree — the SHA alone would
    # otherwise misidentify a locally-modified build as the clean commit.
    if ! git diff --quiet 2>/dev/null || ! git diff --cached --quiet 2>/dev/null; then
        build_sha="${build_sha}-dirty"
    fi
fi
cat > www/pkg/build-info.js <<EOF
// Generated by scripts/build.sh — DO NOT EDIT (regenerated every build, gitignored).
export const BUILD_INFO = { sha: "${build_sha}", builtAt: "${built_at}" };
EOF
echo "Stamped www/pkg/build-info.js: ${build_sha} (${built_at})"

echo
echo "Built www/pkg/ — serve with either:"
echo "  python3 -m http.server -d www 8000"
echo "  basic-http-server www"
echo
echo "Then open http://localhost:8000/ (python) or :4000 (basic-http-server)."
