#!/usr/bin/env python3
"""Generate a www/renderer/<id>-font.js module from a data/<Name>.ch8 file.

A .ch8 is a raw 768-byte 8x8 bitmap font: 96 chars x 8 rows x 1 byte, MSB-left,
covering codepoints 0x20..0x7F only (0x00..0x1F are blank). The emitted module
mirrors the hand-written ones (cushion-font.js, insigbyte-font.js, ...): a
RAW_<NAME> Uint8Array plus expandToRendererFootprint() to the 128x16 = 2048-byte
renderer footprint (each source row emitted twice for the 2x chunky-scanline
upscale), exported as <NAME>_FONT.

Usage:
  scripts/ch8-to-font-module.py "data/ZX Palm.ch8" zx-palm "ZX Palm"

Args: <ch8-path> <font-id (kebab-case)> [display-name]
The display name defaults to the .ch8 basename. Output path is derived from the
font id: www/renderer/<id>-font.js.
"""
import sys
from pathlib import Path

def char_label(cp: int) -> str:
    if cp == 0x20:
        return "' '"
    if cp == 0x7F:
        return "DEL"
    ch = chr(cp)
    if ch == "'":
        return "'\\''"
    if ch == "\\":
        return "'\\\\'"
    return f"'{ch}'"

def main() -> int:
    if len(sys.argv) < 3:
        print(__doc__)
        return 2
    ch8_path = Path(sys.argv[1])
    font_id = sys.argv[2]
    display = sys.argv[3] if len(sys.argv) > 3 else ch8_path.stem

    raw = ch8_path.read_bytes()
    if len(raw) != 768:
        print(f"error: {ch8_path} is {len(raw)} bytes, expected 768", file=sys.stderr)
        return 1

    const = font_id.upper().replace("-", "_")
    repo_root = Path(__file__).resolve().parent.parent
    out_path = repo_root / "www" / "renderer" / f"{font_id}-font.js"

    lines = []
    lines.append(f"// {display} — 8×8 bitmap font, MicroBeast-adjacent provenance.")
    lines.append("//")
    lines.append(f"// Source: {ch8_path.as_posix()} (768 bytes = 96 chars × 8 rows × 1 byte,")
    lines.append("// MSB-left, codepoints 0x20..0x7F only). Codepoints 0x00..0x1F are blank.")
    lines.append("//")
    lines.append("// Storage layout matches the other fonts in the registry: 128 × 16 = 2048")
    lines.append("// bytes, each source row emitted twice for the renderer's chunky-scanline")
    lines.append("// upscale. Generated by scripts/ch8-to-font-module.py.")
    lines.append("")
    lines.append(f"const RAW_{const} = new Uint8Array([")
    for i in range(96):
        cp = i + 32
        row = raw[i * 8 : i * 8 + 8]
        hexes = ", ".join(f"0x{b:02x}" for b in row)
        lines.append(f"    {hexes}, // {cp} {char_label(cp)}")
    lines.append("]);")
    lines.append("")
    lines.append("function expandToRendererFootprint(raw) {")
    lines.append("    const out = new Uint8Array(128 * 16);")
    lines.append("    for (let i = 0; i < 96; i++) {")
    lines.append("        const ch = i + 32;")
    lines.append("        for (let r = 0; r < 8; r++) {")
    lines.append("            const src = raw[i * 8 + r];")
    lines.append("            out[ch * 16 + r * 2 + 0] = src;")
    lines.append("            out[ch * 16 + r * 2 + 1] = src;")
    lines.append("        }")
    lines.append("    }")
    lines.append("    return out;")
    lines.append("}")
    lines.append("")
    lines.append(f"export const {const}_FONT = expandToRendererFootprint(RAW_{const});")
    lines.append("")

    out_path.write_text("\n".join(lines))
    print(f"wrote {out_path.relative_to(repo_root)}  (export {const}_FONT)")
    return 0

if __name__ == "__main__":
    sys.exit(main())
